services:
  - type: web
    name: django-db-app
    env: python
    buildCommand: |
      cd DJANGOPROJ/userdb
      pip install -r ../requirements.txt
    startCommand: gunicorn userdb.userdb.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: userdb.userdb.settings
