services:
  - type: web
    name: userdb-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn userdb.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: userdb.settings
      - key: PYTHON_VERSION
        value: 3.10
